import { ReminderInfo } from './types/ReminderInfo' 
const ReminderList: ReminderInfo[] = [
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 7,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 5,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 1,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
{
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 7,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 5,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 1,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
{
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 7,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 5,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 1,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 10,
  },
  {
    title: 'Lunch with Jane',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 3,
  },
  {
    title: 'Meeting with John',
    description: 'Discuss the new project',
    deadline: '2021-12-01',
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    interval: 2,
  },
]


export { ReminderList }
